/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\HeadphonesTry72.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Headphones(props) {
  const { nodes, materials } = useGLTF("/models/HeadphonesTry72.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh
          geometry={nodes.New_Lowpoly001.geometry}
          material={materials.Cushion2}
        />
        <mesh
          geometry={nodes.New_Lowpoly001_1.geometry}
          material={materials.Leather}
        />
        <mesh
          geometry={nodes.New_Lowpoly001_2.geometry}
          material={materials["Shiny plastic"]}
        />
        <mesh
          geometry={nodes.New_Lowpoly001_3.geometry}
          material={materials.Kraken}
        />
        <mesh
          geometry={nodes.New_Lowpoly001_4.geometry}
          material={materials.Cushion}
        />
        <mesh
          geometry={nodes.New_Lowpoly001_5.geometry}
          material={materials.Cable}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/HeadphonesTry72.glb");
