import type { Metadata } from "next";
import { Poppins, Orbitron } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500"],
});
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="antialiased">
      <body className="font-body overflow-x-hidden bg-[#050506]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
